dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install docker-engine

before_script:
  - docker --version
  - docker-compose up -d --build
  - docker ps -a

script:
  - mvn clean test -Parq-wildfly-remote

after_script:
  - docker-compose down
